### ISSUE TITLE
Join me on LabC group project

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabC-Team1#1]
Join me on LabC group project, implement the EntryWayListInterface.

**Comment by alternatebow** [comment]
Alright sounds good.

**Comment by jillHuang7** [comment]
Cool! And it looks I am automatically joined?

**Comment by karlnicholas** [comment]
Hi guys, great to see you again. It was named team1 to make it unique, but there is nothing that ties it at the moment to "Team1" in the teams area. I'm going to do that now. I'm thrilled to be working with you guys on implementing the interfaces we wrote.
