### ISSUE TITLE
insertHead fails empty list.

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabC-Team1#16]
This code

    iList.insertHead(3);

gives exception:
 
    java.lang.ArrayIndexOutOfBoundsException: -1
        at EntryWayList.insertHead(EntryWayList.java:51)
        at EntryWayListDriver.run(EntryWayListDriver.java:26)
        at EntryWayListDriver.main(EntryWayListDriver.java:18)

**Comment by alternatebow** [comment]
Um... so looking at the insertHead() method

 @Override
    public boolean insertHead(T newEntry) {
        if(numberOfEntries < MAX_CAPACITY){
            for(int i = numberOfEntries - 1; i <= 0; i--){
                this.list[i] = this.list[i + 1]; 
            }
            this.list[0] = newEntry;
            numberOfEntries++;
            return true;
            } 
            return false;
        }

I think we get this error because we are referring to an index of -1. Seeing as the number of entries by default is zero.

**Comment by alternatebow** [comment]
Scratch that last comment. 

But for an empty list we'll run into bounds issue because numberOfEntries start at 0, and thus our i value will be -1.

**Comment by alternatebow** [comment]
Perhaps make a special case for empty lists?

**Comment by karlnicholas** [comment]
Well, I would say that only shift if the list has something in it, so not a special case really but rather shift only if needed.

**Comment by alternatebow** [comment]
Hmm.. yeah that works too. So maybe just insert an extra if statement?

**Comment by karlnicholas** [comment]
Yes, I think that is what is needed.

**Comment by karlnicholas** [comment]
Are you going to be able to fix it?

Get Outlook for iOS




On Fri, Sep 16, 2016 at 5:39 PM -0700, "alternatebow" <notifications@github.com> wrote:





Scratch that last comment.

But for an empty list we'll run into bounds issue because numberOfEntries start at 0, and thus our i value will be -1.

**Comment by alternatebow** [comment]
Working on it right now

**Comment by karlnicholas** [comment]
type in for loop fixed.
