### ISSUE TITLE
review code and sign-off project

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabC-Team1#21]
review code and sign-off project.

**Comment by alternatebow** [comment]
Code looks good to me. Signed off.

**Comment by karlnicholas** [comment]
Looks good to me. Great work everyone.

**Comment by jillHuang7** [comment]
I apologized that I was out of town this weekend. I was trying to connect
to the wifi, but it wasn't work great as I expected...
Really appreciated you guys' great work 😖

**Comment by karlnicholas** [comment]
Hi Jill, I'll take that as a sign-off and close this issue. I promised to upload the project, so I'll do that now.
