### ISSUE TITLE
Implement the interface you wrote for Lab B (EntryWayListInterface).

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabC-Team1#3]
The big kahuna ...

**Comment by karlnicholas** [comment]
Created initial EntryWayList class. Added constructors and an array. I would like to implement it with an internal (if not external) Zero based position logic. I copied some of the code from AList, but removed some of the silly stuff.

**Comment by alternatebow** [comment]
So we are going with a Arraylist data type to implement this?

**Comment by karlnicholas** [comment]
Can we?

**Comment by alternatebow** [comment]
I thought we could. Said so on the assignment. 

"Your implementation can use either an expandable array or linked nodes- it is your choice."

**Comment by karlnicholas** [comment]
Right, but expandable array means T[] and linked Nodes = class Node{} ...

**Comment by alternatebow** [comment]
K. My bad, I interpreted that wrong. So expandable array it is. So what's something that needs work on?

**Comment by karlnicholas** [comment]
Pick and choose. All of the methods are unimplemented I think.

**Comment by karlnicholas** [comment]
I think everything is implemented. For the `contains` question I think we are still undecided. Returning a boolean as it was originally coded might well be the best because then it works in a simple if statement. Returning a T doesn't seem helpful because it's only returning what was passed in and it can't be passed on to any other method. I had changed it to int because of the comments, then to T after thinking int was no good, and now I think that the original boolean is best and it was the comments that needed to be updated, not the code. Thoughts?

**Comment by alternatebow** [comment]
Lol. Alrighty then, so we're going back to Boolean? That sounds logical to
me.

**Comment by karlnicholas** [comment]
Coding with a sense of humor! Does it get any better???

 

So, you put your original code back in then?

**Comment by alternatebow** [comment]
When I get back home. In lecture now. Unless someone else wants to make the change.

**Comment by karlnicholas** [comment]
No hurries. Anyone can do it.

**Comment by karlnicholas** [comment]
Looking good: :100:
